version : '2'
services:
  springappserver:
    container_name: springappserver
    build:
      context: .
      dockerfile: springapp-dockerfile
    ports:
      - "8080:8080"
    networks:
      - net-spring-db
    volumes:
      - /vol/development
    depends_on:
      - mysqldbserver
    links:
      - mysqldbserver

  mysqldbserver:
    container_name: mysqldbserver
    build:
      context: .
      dockerfile: mysqldb-dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=todoItem"
      - "MYSQL_ROOT_HOST=%"
    ports:
          - "3306:3306"
    restart: always
    networks:
        - net-spring-db
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]


networks:
  net-spring-db:
    driver: bridge

#  mysqldbserver:
#    container_name: mysqldbserver
#    build:
#      context: .
#      dockerfile: mysqldb-dockerfile
#    environment:
#      - 'MYSQL_ROOT_PASSWORD=test'
#      - 'MYSQL_DATABASE=todoItem'
#      - 'MYSQL_ROOT_HOST=%'
#    ports:
#      - "3308:3308"
#    restart: always
#    networks:
#      - net-spring-db


#    command: [
#      'mysqld',
#      '--innodb-buffer-pool-size=20M',
#      '--character-set-server=utf8',
#      '--collation-server=utf8_general_ci',
#      '--default-time-zone=+8:00',
#      '--lower-case-table-names=1'
#    ]

#  - "MYSQL_ROOT_PASSWORD=test"
#    - "MYSQL_DATABASE=todoItem"
#    - "MYSQL_USER=root"
#    - "MYSQL_PASSWORD=root"
