spring:
  datasource:
    url: jdbc:mysql://mysqldbserver:3306/todoItem?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  port:
    8080

#        spring.jpa.hibernate.ddl-auto=update
#        # Enable this line to use camel cased name mapping.
#        spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#
#        spring.jpa.properties.hibernate.format_sql=true
#
#        # We would like to use logger to display SQL in the console since it will also display the
#        # binded arguments. We turn off spring framework log to avoid verbose message.
#        logging.level.org.springframework=OFF
#        logging.level.root=OFF
#        logging.level.org.hibernate.SQL=DEBUG
#        logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
#        hibernate.jdbc.time_zone=UTC
#        spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#        spring.datasource.url=jdbc:mysql://mysqldbserver:3306/todoItem?useUnicode=true&characterEncoding=UTF-8
#        spring.datasource.username=root
#        spring.datasource.password=root
#        #spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#        #hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#        #hibernate.hbm2ddl.auto=update
#
#
#        server.port=8080
